/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static wyjscie  result;
	




	char *str = argp->x1;
    char t[2*argp->x2];

	
    
	
    for (int i = 0; i <=argp->x2; i++)
    {
        snprintf(t+i*2, sizeof(t)-2*(i)+1, "%02x", str[i]);
    }
    
	printf("\nHalo halo to ja serwer 'Proces2'  \nZwracam ci wartosc w hexa = \t%s",t);



	/*
	 * insert server code here
	 */

	// for(int i=0; i < argp->x2 ;i++)
	// {
	// 	printf("%02X",dana[i]);
		
	// }
	
	fflush(stdout);

	//result.suma    = argp->x1 + argp->x2;
	//result.roznica = argp->x1 - argp->x2;
	//result.iloczyn = argp->x1 * argp->x2;

	return &result;
}
