/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"


#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>
  
#define PORT     8080
#define MAXLINE 1024


wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static wyjscie  result;
	




	char *str = argp->x1;
    char t[2*argp->x2];

	
    
	
    for (int i = 0; i <=argp->x2; i++)
    {
        snprintf(t+i*2, sizeof(t)-2*(i)+1, "%02x", str[i]);
    }
    
	printf("\nHalo halo to ja serwer 'Proces2'  \nZwracam ci wartosc w hexa = \t%s",t);



	/*
	 * insert server code here
	 */

	// for(int i=0; i < argp->x2 ;i++)
	// {
	// 	printf("%02X",dana[i]);
		
	// }
	
	fflush(stdout);

	//result.suma    = argp->x1 + argp->x2;
	//result.roznica = argp->x1 - argp->x2;
	//result.iloczyn = argp->x1 * argp->x2;



    int sockfd;
    char buffer[MAXLINE];
    char *hello = t;
    struct sockaddr_in     servaddr;
  
    // Creating socket file descriptor
    if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) {
        perror("socket creation failed");
        exit(EXIT_FAILURE);
    }
  
    memset(&servaddr, 0, sizeof(servaddr));
      
    // Filling server information
    servaddr.sin_family = AF_INET;
    servaddr.sin_port = htons(PORT);
    servaddr.sin_addr.s_addr = INADDR_ANY;
      
    int n, len;
      
    sendto(sockfd, (const char *)hello, strlen(hello),
        MSG_CONFIRM, (const struct sockaddr *) &servaddr, 
            sizeof(servaddr));
    // printf("Hello message sent.\n");
          
    // n = recvfrom(sockfd, (char *)buffer, MAXLINE, 
    //             MSG_WAITALL, (struct sockaddr *) &servaddr,
    //             &len);
    // buffer[n] = '\0';
    // printf("Server : %s\n", buffer);
  
    close(sockfd);







	return &result;
}
